# golangci-lint configuration file
# See: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

issues:
  exclude-dirs:
    - vendor
  exclude-files:
    - ".*\\.pb\\.go$"

output:
  formats:
    - format: colored-line-number
      print-issued-lines: true
      print-linter-name: true

linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 150
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/cristobalcontreras/gos
  funlen:
    lines: 120
    statements: 70

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - misspell

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec

    # Ignore error checking for color print functions (cosmetic output)
    - text: "Error return value of.*Println.*is not checked"
      linters:
        - errcheck

    - text: "Error return value of.*Printf.*is not checked"
      linters:
        - errcheck

    # Allow init functions in cmd package for cobra
    - path: cmd/
      text: "don't use `init` function"

    # Allow security issues for CLI tool
    - text: "G204:"
    - text: "G301:"
    - text: "G302:"
    - text: "G304:"
    - text: "G306:"

  max-issues-per-linter: 0
  max-same-issues: 0
