# This file was generated by GoReleaser. DO NOT EDIT.
cask "gos" do
  desc "A comprehensive Go version manager CLI"
  homepage "https://github.com/chrisloarryn/homebrew-gos"
  version "0.0.24"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gos"

  on_macos do
    url "https://github.com/chrisloarryn/homebrew-gos/releases/download/v0.0.24/gos_Darwin_all.tar.gz"
    sha256 "d1b5e618277cadf3402b2d7968d02e75428aa72f6de39a73237022c9e3719841"
  end

  on_linux do
    on_intel do
      url "https://github.com/chrisloarryn/homebrew-gos/releases/download/v0.0.24/gos_Linux_x86_64.tar.gz"
      sha256 "1c50cedf4a190467eef0ffcbc08daea48b9b4e2213bc4b0f4fbd07bfdd796221"
    end
    on_arm do
      url "https://github.com/chrisloarryn/homebrew-gos/releases/download/v0.0.24/gos_Linux_arm64.tar.gz"
      sha256 "eda4b241a7d41975e50f70450c7b8c423057689cdda8431697f07b37f8a46ac3"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gos"]
    end
  end

  caveats do
    "After installation, run:"
    "  gos setup"
  end

  # No zap stanza required
end
