# This file was generated by GoReleaser. DO NOT EDIT.
cask "gos" do
  desc "A comprehensive Go version manager CLI"
  homepage "https://github.com/chrisloarryn/homebrew-gos"
  version "0.0.25"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gos"

  on_macos do
    url "https://github.com/chrisloarryn/homebrew-gos/releases/download/v0.0.25/gos_Darwin_all.tar.gz"
    sha256 "74a8998b223a654beb2b3037c6e926fb22b1dd74b067e3870041bee1aab8fe5d"
  end

  on_linux do
    on_intel do
      url "https://github.com/chrisloarryn/homebrew-gos/releases/download/v0.0.25/gos_Linux_x86_64.tar.gz"
      sha256 "7b8a2c2fe55b64aa3adbee9c44e289030d076841c9175bcd6c52d0db28899083"
    end
    on_arm do
      url "https://github.com/chrisloarryn/homebrew-gos/releases/download/v0.0.25/gos_Linux_arm64.tar.gz"
      sha256 "5715d9da5e2293bc45bbd025a05492f9e392e9cc81ad320fc3a230f3cfca29c7"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gos"]
    end
  end

  caveats do
    "After installation, run:"
    "  gos setup"
  end

  # No zap stanza required
end
