# This file was generated by GoReleaser. DO NOT EDIT.
cask "gos" do
  desc "A comprehensive Go version manager CLI"
  homepage "https://github.com/chrisloarryn/homebrew-gos"
  version "0.0.22"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gos"

  on_macos do
    url "https://github.com/chrisloarryn/homebrew-gos/releases/download/v0.0.22/gos_Darwin_all.tar.gz"
    sha256 "ac72aafe252270e6856eeb1db3865407110e3a0e205dc11246deea9c6a6956bd"
  end

  on_linux do
    on_intel do
      url "https://github.com/chrisloarryn/homebrew-gos/releases/download/v0.0.22/gos_Linux_x86_64.tar.gz"
      sha256 "97063846a3f97451b65197b3a762287914bece6f9e78dd994280c570a44cbcd2"
    end
    on_arm do
      url "https://github.com/chrisloarryn/homebrew-gos/releases/download/v0.0.22/gos_Linux_arm64.tar.gz"
      sha256 "32f70eaf813ba367f6cd79bd11e10262e680a9d1535a9b799741597b239281f0"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gos"]
    end
  end

  caveats do
    "After installation, run:"
    "  gos setup"
  end

  # No zap stanza required
end
