# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gos < Formula
  desc "A comprehensive Go version manager CLI"
  homepage "https://github.com/chrisloarryn/homebrew-gos"
  version "0.0.13"
  license "MIT"

  depends_on "curl"
  depends_on "git" => :optional

  on_macos do
    url "https://github.com/chrisloarryn/homebrew-gos/releases/download/v0.0.13/gos_Darwin_all.tar.gz"
    sha256 "facaa0528edbaa59110e1278e5e9d263e4fbfddff69098f4af4c4356a870196f"

    def install
      bin.install "gos"

      # Install completion scripts
      generate_completions_from_executable(bin/"gos", "completion")
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/chrisloarryn/homebrew-gos/releases/download/v0.0.13/gos_Linux_x86_64.tar.gz"
      sha256 "4cc7e87e6f764cecd16fff0440ee20742dbd2a4ee28db1cddda065f9ec28008d"
      def install
        bin.install "gos"

        # Install completion scripts
        generate_completions_from_executable(bin/"gos", "completion")
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/chrisloarryn/homebrew-gos/releases/download/v0.0.13/gos_Linux_armv6.tar.gz"
      sha256 "16f4206e28b20d980f4e040e8ae29a3c6f680c69ffe1f4e489ecb150fe98216d"
      def install
        bin.install "gos"

        # Install completion scripts
        generate_completions_from_executable(bin/"gos", "completion")
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/chrisloarryn/homebrew-gos/releases/download/v0.0.13/gos_Linux_arm64.tar.gz"
      sha256 "3e87c6f4dca59944681f10e716637c8070619dc4e59506f28bfc6d84fdd2382c"
      def install
        bin.install "gos"

        # Install completion scripts
        generate_completions_from_executable(bin/"gos", "completion")
      end
    end
  end

  test do
    system "#{bin}/gos --help"
  end
end
