# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gos < Formula
  desc "A comprehensive Go version manager CLI"
  homepage "https://github.com/chrisloarryn/homebrew-gos"
  version "0.0.14"
  license "MIT"

  depends_on "curl"
  depends_on "git" => :optional

  on_macos do
    url "https://github.com/chrisloarryn/homebrew-gos/releases/download/v0.0.14/gos_Darwin_all.tar.gz"
    sha256 "39e6ed2b1807a2a18686a764213b1cb53181dc7a64e447a9709fc8de6f00ed91"

    def install
      bin.install "gos"

      # Install completion scripts
      generate_completions_from_executable(bin/"gos", "completion")
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/chrisloarryn/homebrew-gos/releases/download/v0.0.14/gos_Linux_x86_64.tar.gz"
      sha256 "48cf61ab7f31b4139275715c4b71290df35296228e99806b717938b18a68702a"
      def install
        bin.install "gos"

        # Install completion scripts
        generate_completions_from_executable(bin/"gos", "completion")
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/chrisloarryn/homebrew-gos/releases/download/v0.0.14/gos_Linux_armv6.tar.gz"
      sha256 "fcb21d0c8af47899718ddf5dc3b323ef562a7835fc19845997e40d2606b70e10"
      def install
        bin.install "gos"

        # Install completion scripts
        generate_completions_from_executable(bin/"gos", "completion")
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/chrisloarryn/homebrew-gos/releases/download/v0.0.14/gos_Linux_arm64.tar.gz"
      sha256 "3d78cf2c631ff08ee3593cef475c43e379a0c44134e99677a268d4336fd6fb0f"
      def install
        bin.install "gos"

        # Install completion scripts
        generate_completions_from_executable(bin/"gos", "completion")
      end
    end
  end

  test do
    system "#{bin}/gos --help"
  end
end
