# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gos < Formula
  desc "A comprehensive Go version manager CLI"
  homepage "https://github.com/chrisloarryn/homebrew-gos"
  version "0.0.15"
  license "MIT"

  depends_on "curl"
  depends_on "git" => :optional

  on_macos do
    url "https://github.com/chrisloarryn/homebrew-gos/releases/download/v0.0.15/gos_Darwin_all.tar.gz"
    sha256 "2c5b01562019110baa8c8302018baf2f0132fac88babb7f278c07c499a7210e4"

    def install
      bin.install "gos"

      # Install completion scripts
      generate_completions_from_executable(bin/"gos", "completion")
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/chrisloarryn/homebrew-gos/releases/download/v0.0.15/gos_Linux_x86_64.tar.gz"
      sha256 "f6428a0d817e162682f70173fad53b9ee5ce72dbd01af8d03f058d967cadd8e8"
      def install
        bin.install "gos"

        # Install completion scripts
        generate_completions_from_executable(bin/"gos", "completion")
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/chrisloarryn/homebrew-gos/releases/download/v0.0.15/gos_Linux_armv6.tar.gz"
      sha256 "06544bec940f1a794dbb9f62b31d359c06ba36efd061013e664d7f044c32056d"
      def install
        bin.install "gos"

        # Install completion scripts
        generate_completions_from_executable(bin/"gos", "completion")
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/chrisloarryn/homebrew-gos/releases/download/v0.0.15/gos_Linux_arm64.tar.gz"
      sha256 "ba497cda355027666822b5866934b0b5561ac2ccbe4dc41601424e12de29534b"
      def install
        bin.install "gos"

        # Install completion scripts
        generate_completions_from_executable(bin/"gos", "completion")
      end
    end
  end

  test do
    system "#{bin}/gos --help"
  end
end
